<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.3" />
    <PackageReference Include="System.Data.OleDb" Version="9.0.4" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(SolutionDir)GISControlWPFGL2\Shader\*&quot; &quot;$(TargetDir)Shader\&quot; /E /Y /I&#xD;&#xA;xcopy &quot;$(SolutionDir)GISControlWPFGL2\shp\*&quot; &quot;$(TargetDir)shp\&quot; /E /Y /I" />
  </Target>

</Project>
